/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.CodeReview;

/**
 *
 * @author Aviad
 */
public class dlgReviews extends javax.swing.JDialog {

    /**view field*/
    private ViewLogic view;
    
    private UserMain userMain;
    
    private ArrayList<CodeReview> codeReviews;
    /**
     * Creates new form dlgReviews
     * @param userMain
     * @param codeReviews
     * @param modal
     * @param view
     */
    public dlgReviews(UserMain userMain, ArrayList<CodeReview> codeReviews, boolean modal ,ViewLogic view) {
        super(userMain, modal);
        this.userMain = userMain;
        this.codeReviews = codeReviews;
        this.view = view;
        initComponents();
        this.setLocation( userMain.getLocation().x+(userMain.getWidth()+8) , userMain.getLocation().y-1);
        DefaultListModel<CodeReview> modle = new DefaultListModel<CodeReview>(); 
            for(CodeReview review : this.codeReviews)
            {
                modle.addElement(review);
            }
            ReviewList.setModel(modle);
            cbLanguage.addItem("--All--");
        for(String language : view.getAllLanguages())
            {
            cbLanguage.addItem(language);
            }  
    }
    
    private void sortReviewList(){
        DefaultListModel<CodeReview> modle = new DefaultListModel<CodeReview>();
        String lang = (String)cbLanguage.getSelectedItem();
        int rating = cbRating.getSelectedIndex();
        if(lang.equals("--All--") &&  rating < 1){
            for(CodeReview review : this.codeReviews)
            {
                modle.addElement(review);
            }
        }else if(!lang.equals("--All--") && rating < 1){
            for(CodeReview review : this.codeReviews)
            {
                if(review.getFile().getLanguage().equals(lang)){
                modle.addElement(review);
                }
            }
        } else if(lang.equals("--All--") && rating > 1){
            for(CodeReview review : this.codeReviews)
            {
                if(review.getCodeRating() == rating ){
                modle.addElement(review);
                }
            }
        }else if(!lang.equals("--All--") && rating > 1){
            for(CodeReview review : this.codeReviews)
            {
                if(review.getFile().getLanguage().equals(lang) && review.getCodeRating() == rating ){
                modle.addElement(review);
                }
            }
        }
  
            ReviewList.setModel(modle); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReviewList = new javax.swing.JList<>();
        plSortBy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbLanguage = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbRating = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 153, 153));
        setModalExclusionType(null);
        setModalityType(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Choose Review:");

        ReviewList.setBackground(new java.awt.Color(102, 102, 102));
        ReviewList.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ReviewList.setForeground(new java.awt.Color(255, 255, 255));
        ReviewList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReviewListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ReviewList);

        plSortBy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sort By: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Language:");

        cbLanguage.setBackground(new java.awt.Color(102, 102, 102));
        cbLanguage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbLanguage.setForeground(new java.awt.Color(255, 255, 255));
        cbLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLanguageItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Quality Rating:");

        cbRating.setBackground(new java.awt.Color(102, 102, 102));
        cbRating.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbRating.setForeground(new java.awt.Color(255, 255, 255));
        cbRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--All--", "1", "2", "3", "4", "5" }));
        cbRating.setSelectedIndex(-1);
        cbRating.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRatingItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout plSortByLayout = new javax.swing.GroupLayout(plSortBy);
        plSortBy.setLayout(plSortByLayout);
        plSortByLayout.setHorizontalGroup(
            plSortByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plSortByLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        plSortByLayout.setVerticalGroup(
            plSortByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plSortByLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plSortByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plSortBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReviewListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReviewListMouseClicked
        if (evt.getClickCount() == 2) {
            if(this.ReviewList.getSelectedValue() != null){
                frmDisplayReview displayReview = new frmDisplayReview(userMain,view, this.ReviewList.getSelectedValue());
                displayReview.setVisible(true);
                this.dispose();     
                userMain.setVisible(false);
               
            }

        }
        
    }//GEN-LAST:event_ReviewListMouseClicked

    private void cbLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLanguageItemStateChanged
        sortReviewList();
    }//GEN-LAST:event_cbLanguageItemStateChanged

    private void cbRatingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRatingItemStateChanged
        sortReviewList();
    }//GEN-LAST:event_cbRatingItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dlgReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(dlgReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(dlgReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(dlgReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                dlgReviews dialog = new dlgReviews(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<CodeReview> ReviewList;
    private javax.swing.JComboBox<String> cbLanguage;
    private javax.swing.JComboBox<String> cbRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel plSortBy;
    // End of variables declaration//GEN-END:variables
}
