/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Bug;
import model.CodeFile;
import utils.E_ScoreManager;
import utils.StarRater;

/**
 *
 * @author Aviad
 */
public class frmNewReview extends javax.swing.JFrame {

    /**view field*/
    private ViewLogic view;
    
    private UserMain main;
    
    private dlgAddBug addBug;
    
    private frmReviewCodeEditor reviewCodeEditor;
    
    private ArrayList <Bug> bugs;
    
    private ArrayList <CodeFile> codeFiles;
    
    private CodeFile codeFile;
    /**
     * Creates new form frmNewReview
     * @param view
     * @param frame
     * @param codeFiles
     */
    public frmNewReview(ViewLogic view,javax.swing.JFrame frame, ArrayList <CodeFile> codeFiles) {
        this.main = (UserMain)frame;
        this.view = view;
        bugs = new ArrayList<Bug>();
        this.codeFiles = codeFiles;
        initComponents();
        setLocation();
        this.setTitle("Write Review"); //the title of the frame
        for(CodeFile file : codeFiles){
            this.cbFilesToReview.addItem(file.getSerialNumber()+" <"+file.getFileName()+">");
        }
        
    }
    private void setLocation(){
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDisplayCode = new javax.swing.JButton();
        starRater = new StarRater(5,0);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        shareCheckBox = new javax.swing.JCheckBox();
        btnAddBug = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSuggestionsAndTips = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        BugList = new javax.swing.JList<>();
        btnRemoveBug = new javax.swing.JButton();
        cbFilesToReview = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(403, 683));
        setPreferredSize(new java.awt.Dimension(403, 683));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Display code:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 92, 103, 21);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quality rating:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 133, 109, 21);

        btnDisplayCode.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDisplayCode.setText("...");
        btnDisplayCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplayCode);
        btnDisplayCode.setBounds(199, 92, 26, 23);

        starRater.setOpaque(false);

        javax.swing.GroupLayout starRaterLayout = new javax.swing.GroupLayout(starRater);
        starRater.setLayout(starRaterLayout);
        starRaterLayout.setHorizontalGroup(
            starRaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        starRaterLayout.setVerticalGroup(
            starRaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        getContentPane().add(starRater);
        starRater.setBounds(199, 133, 106, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Suggestions and tips:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 385, 164, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Bug:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 173, 68, 21);

        shareCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        shareCheckBox.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        shareCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        shareCheckBox.setText("Share? ");
        shareCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shareCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        shareCheckBox.setOpaque(false);
        getContentPane().add(shareCheckBox);
        shareCheckBox.setBounds(10, 549, 83, 29);

        btnAddBug.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddBug.setText("+");
        btnAddBug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBugActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBug);
        btnAddBug.setBounds(90, 170, 50, 25);

        taSuggestionsAndTips.setBackground(new java.awt.Color(102, 102, 102));
        taSuggestionsAndTips.setColumns(20);
        taSuggestionsAndTips.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        taSuggestionsAndTips.setForeground(new java.awt.Color(255, 255, 255));
        taSuggestionsAndTips.setRows(5);
        jScrollPane1.setViewportView(taSuggestionsAndTips);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 412, 383, 130);

        BugList.setBackground(new java.awt.Color(102, 102, 102));
        BugList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BugList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(BugList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 208, 383, 130);

        btnRemoveBug.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRemoveBug.setText("Remove This Bug?");
        btnRemoveBug.setEnabled(false);
        btnRemoveBug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBugActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveBug);
        btnRemoveBug.setBounds(10, 344, 150, 23);

        cbFilesToReview.setBackground(new java.awt.Color(102, 102, 102));
        cbFilesToReview.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbFilesToReview.setForeground(new java.awt.Color(255, 255, 255));
        cbFilesToReview.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFilesToReviewItemStateChanged(evt);
            }
        });
        cbFilesToReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilesToReviewActionPerformed(evt);
            }
        });
        getContentPane().add(cbFilesToReview);
        cbFilesToReview.setBounds(199, 41, 183, 29);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select File To Review:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 44, 171, 21);

        btnSend.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend);
        btnSend.setBounds(83, 611, 90, 28);

        btnCancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(240, 611, 90, 28);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grey-Background.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBugActionPerformed
       addBug = new dlgAddBug(this, true);
       addBug.setVisible(true);
    }//GEN-LAST:event_btnAddBugActionPerformed

    private void btnRemoveBugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBugActionPerformed
        bugs.remove(BugList.getSelectedIndex());
        ((DefaultListModel<String>)BugList.getModel()).remove(BugList.getSelectedIndex());
        if( ((DefaultListModel<String>)BugList.getModel()).isEmpty())
        {
            this.btnRemoveBug.setEnabled(false);
        }
    }//GEN-LAST:event_btnRemoveBugActionPerformed

    private void btnDisplayCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCodeActionPerformed
        reviewCodeEditor = new frmReviewCodeEditor(this.getLocationOnScreen(),this.getWidth()+5,this.codeFile.getFileAttached());
        reviewCodeEditor.setVisible(true);
    }//GEN-LAST:event_btnDisplayCodeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if(reviewCodeEditor!=null &&reviewCodeEditor.isVisible())
        {
        reviewCodeEditor.dispose();
        }
        this.main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        view.addCodeReview(codeFile.getSerialNumber(), this.codeFile, codeFile.getDate(), ((StarRater)starRater).getSelection(), bugs, this.taSuggestionsAndTips, shareCheckBox, this);
        if(reviewCodeEditor!=null)
        {
        reviewCodeEditor.dispose();
        }
        this.main.RefreshScore();
        this.main.RefreshOutside();
        this.main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSendActionPerformed

    private void cbFilesToReviewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFilesToReviewItemStateChanged
        try{
        if(this.reviewCodeEditor.isActive())
        {
            this.reviewCodeEditor.dispose();
            
        }
        }catch(Exception e){}
        this.codeFile = codeFiles.get(cbFilesToReview.getSelectedIndex());
    }//GEN-LAST:event_cbFilesToReviewItemStateChanged

    private void cbFilesToReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilesToReviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilesToReviewActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       int rate= ((StarRater)starRater).getSelection();
       String tip= taSuggestionsAndTips.getText();
       if(rate>0 || tip.length()>0 ||bugs.size()>0||shareCheckBox.isSelected())
       {
           cbFilesToReview.setEnabled(false);
       }
       else
       {
          cbFilesToReview.setEnabled(true); 
       }
    }//GEN-LAST:event_formMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{ 
        reviewCodeEditor.dispose();
        }
        catch(Exception e)
        {}
            
       
        this.main.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    public void AddBug(Bug bug) {
         int i = 0;
         if(bug != null){
             bugs.add(bug);   
          DefaultListModel<String> modle = new DefaultListModel<String>(); 
            for(Bug b : bugs)
            {  
                modle.addElement((++i)+"."+b.getBugsDescription());
            }
            BugList.setModel(modle);
         }  
    }
    
    public void IsRemoveBugEnabled(boolean bool) {
        this.btnRemoveBug.setEnabled(bool);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmNewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmNewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmNewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmNewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmNewReview(ViewLogic.getInstance()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> BugList;
    private javax.swing.JButton btnAddBug;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDisplayCode;
    private javax.swing.JButton btnRemoveBug;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> cbFilesToReview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox shareCheckBox;
    private javax.swing.JPanel starRater;
    private javax.swing.JTextArea taSuggestionsAndTips;
    // End of variables declaration//GEN-END:variables
}
