package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Programmer;
import model.Team;

/**
 *
 * @author maayanezra
 */

public class IfrmTeamProfile extends javax.swing.JFrame {
private static final long serialVersionUID = 1L;
   /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
  
    private Team team;
    private ArrayList<Programmer> progMembers;
    private ArrayList<String> progMembersNames;
    private ArrayList<Team> contriTeams;
    private ArrayList<String> contriTeamNames;
    private String teamRank;
    /**
     * Creates new form IfrmTeamProfile
     * @param view
     */
    public IfrmTeamProfile(ViewLogic view) {
        
        this.view = view;
        team=ViewLogic.getUserTeam();
       if(team.getScore()<100)
       {
           teamRank="Village";
       }
       else if(team.getScore()>=100&&team.getScore()<250)
       {
           teamRank="Castle";
       }
        else if(team.getScore()>=250)
       {
           teamRank="Empire";
       }
          
        initComponents();
        setLocation();
        contriTeams = view.getContributedTeams(team);
        setTitle("Team Profile"); //the title of the frame
        progMembers = team.getTeamMembers();
        view.setImag(this.TeamIcon, ViewLogic.getUserTeam().getTeamSymbol());
        DefaultListModel<String> modle = new DefaultListModel<String>();
        progMembersNames= new ArrayList<>();
        contriTeamNames=new ArrayList<>();
        for(Programmer prNames :progMembers)
        {
           progMembersNames.add(prNames.getFirstName()+" "+prNames.getLastName());
        }
        
         for(String memberName : progMembersNames)
            {
                modle.addElement(memberName);
            }

        members.setModel(modle);
            
         DefaultListModel<String> modle2 = new DefaultListModel<String>();
        for(Team teamName :contriTeams)
        {
           contriTeamNames.add(teamName.getTeamName()+" score: "+teamName.getScore());
        }
        
         for(String teamsNames : contriTeamNames)
            {
                modle2.addElement(teamsNames);
            }

        teams.setModel(modle2);
        
    }
    private void setLocation(){
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        members = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teams = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        TeamIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(413, 728));
        setPreferredSize(new java.awt.Dimension(413, 728));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Team "+this.team.getTeamName()+" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 280, 33);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Team score: "+team.getScore()+" ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 240, 31);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html> Team leader: "+  team.getTeamLeader().getFirstName()+" "+team.getTeamLeader().getLastName()+" <br>Rank: "+teamRank+"</html>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 370, 70);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your team contributed to: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 400, 298, 31);

        members.setBackground(new java.awt.Color(153, 153, 153));
        members.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        members.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        members.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(members);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 342, 108);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Team members:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 220, 183, 31);

        teams.setBackground(new java.awt.Color(153, 153, 153));
        teams.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        teams.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        teams.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(teams);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 440, 342, 120);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jButton1.setText("Back to profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 610, 180, 33);

        TeamIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(TeamIcon);
        TeamIcon.setBounds(290, 10, 100, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grey-Background.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 410, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TeamIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList members;
    private javax.swing.JList teams;
    // End of variables declaration//GEN-END:variables
}
