/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.util.ArrayList;

import model.Programmer;
import model.Team;



/**
 *
 * @author Aviad
 */
public class IfrmRemoveTeam extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private javax.swing.JDesktopPane myDesk;
    
    
    private ArrayList<Team> teams;
    
    /**
     * Creates new form IfrmRemoveProgrammer
     * @param view
     * @param myDesk
     */
    public IfrmRemoveTeam(ViewLogic view, javax.swing.JDesktopPane myDesk) {
        this.myDesk = myDesk;
        this.view = view;
        initComponents();
        setTitle("Remove Team"); //the title of the frame
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        this.setSize(desktopSize);
        teams = view.getAllTeams();
        for(Team t :teams)
            {
            cbTeamID.addItem(t.getTeamNumber()+"");
            }
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemove = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dPanel = new javax.swing.JPanel();
        txtMail = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtProgrammerID = new javax.swing.JTextField();
        iconFrame = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        txtTeamName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbTeamID = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRemove.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 492, 100, 31));

        btnCancel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 492, 100, 31));

        dPanel.setBackground(new java.awt.Color(204, 204, 204));
        dPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team Leader: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        dPanel.setOpaque(false);

        txtMail.setEditable(false);
        txtMail.setBackground(new java.awt.Color(102, 102, 102));
        txtMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMail.setForeground(new java.awt.Color(255, 255, 255));
        txtMail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtMail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtFirstName.setEditable(false);
        txtFirstName.setBackground(new java.awt.Color(102, 102, 102));
        txtFirstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        txtLastName.setEditable(false);
        txtLastName.setBackground(new java.awt.Color(102, 102, 102));
        txtLastName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("E-Mail:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("First Name:");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Programmer ID:");

        txtProgrammerID.setEditable(false);
        txtProgrammerID.setBackground(new java.awt.Color(102, 102, 102));
        txtProgrammerID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtProgrammerID.setForeground(new java.awt.Color(255, 255, 255));
        txtProgrammerID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        javax.swing.GroupLayout dPanelLayout = new javax.swing.GroupLayout(dPanel);
        dPanel.setLayout(dPanelLayout);
        dPanelLayout.setHorizontalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(76, 76, 76)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProgrammerID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        dPanelLayout.setVerticalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProgrammerID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );

        getContentPane().add(dPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 213, -1, 197));

        iconFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(iconFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 160, 160));

        lbIcon.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbIcon.setText("Team Icon:");
        getContentPane().add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        txtTeamName.setEditable(false);
        txtTeamName.setBackground(new java.awt.Color(102, 102, 102));
        txtTeamName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTeamName.setForeground(new java.awt.Color(255, 255, 255));
        txtTeamName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtTeamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 169, 180, 26));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Team Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 170, -1, -1));

        cbTeamID.setBackground(new java.awt.Color(102, 102, 102));
        cbTeamID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbTeamID.setOpaque(false);
        cbTeamID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTeamIDItemStateChanged(evt);
            }
        });
        getContentPane().add(cbTeamID, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 125, 180, 26));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("Team ID:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 127, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grayNoobwallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

        view.removeTeam(cbTeamID, txtTeamName, this);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbTeamIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTeamIDItemStateChanged
        Team team = teams.get(this.cbTeamID.getSelectedIndex());
        this.txtTeamName.setText(team.getTeamName());
        view.setImag(this.iconFrame, team.getTeamSymbol());
        Programmer pro =  team.getTeamLeader();
        txtProgrammerID.setText(pro.getId());
        txtFirstName.setText(pro.getFirstName());
        txtLastName.setText(pro.getLastName());
        txtMail.setText(pro.getEmail());
    }//GEN-LAST:event_cbTeamIDItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbTeamID;
    private javax.swing.JPanel dPanel;
    private javax.swing.JLabel iconFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtProgrammerID;
    private javax.swing.JTextField txtTeamName;
    // End of variables declaration//GEN-END:variables
}
