/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import model.ExpertProgrammer;
import model.Programmer;
import utils.SoundClass;
/**
 *
 * @author Aviad
 */
public class IfrmRemoveProgrammer extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private javax.swing.JDesktopPane myDesk;
    
    
    private ArrayList<Programmer> prog;
    
    /**
     * Creates new form IfrmRemoveProgrammer
     * @param view
     * @param myDesk
     */
    public IfrmRemoveProgrammer(ViewLogic view, javax.swing.JDesktopPane myDesk) {
            this.myDesk = myDesk;
            this.view = view;
            initComponents();
            //this.iconFrame.setVisible(false);
            this.plExpert.setVisible(false);
            this.dPanel.setVisible(false);
            this.cbID.requestFocusInWindow();
            prog=view.getAllProgrammers();
            setTitle("Remove Programmer"); //the title of the frame
            Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
            this.setSize(desktopSize);
            for(Programmer pr :prog)
            {
            cbID.addItem(pr.getId());
            }
           
            ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        cbID = new javax.swing.JComboBox<>();
        dPanel = new javax.swing.JPanel();
        txtMail = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lbIcon = new javax.swing.JLabel();
        IsExpertCheckBox = new javax.swing.JCheckBox();
        plExpert = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LanguagesJList = new javax.swing.JList<>();
        ProgrammingLanguages = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iconFrame = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRemove.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 558, 100, 31));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        btnCancel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 558, 100, 31));

        cbID.setBackground(new java.awt.Color(102, 102, 102));
        cbID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbID.setOpaque(false);
        cbID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIDItemStateChanged(evt);
            }
        });
        getContentPane().add(cbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 180, 26));

        dPanel.setBackground(new java.awt.Color(204, 204, 204));
        dPanel.setOpaque(false);
        dPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMail.setEditable(false);
        txtMail.setBackground(new java.awt.Color(102, 102, 102));
        txtMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMail.setForeground(new java.awt.Color(255, 255, 255));
        txtMail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtMail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dPanel.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 83, 180, 26));

        txtFirstName.setEditable(false);
        txtFirstName.setBackground(new java.awt.Color(102, 102, 102));
        txtFirstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        dPanel.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 19, 180, 26));

        txtLastName.setEditable(false);
        txtLastName.setBackground(new java.awt.Color(102, 102, 102));
        txtLastName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        dPanel.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 51, 180, 26));

        lbIcon.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbIcon.setText("Icon:");
        dPanel.add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 11, -1, -1));

        IsExpertCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        IsExpertCheckBox.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IsExpertCheckBox.setText("Is Expert:  ");
        IsExpertCheckBox.setEnabled(false);
        IsExpertCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        IsExpertCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IsExpertCheckBox.setOpaque(false);
        IsExpertCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsExpertCheckBoxActionPerformed(evt);
            }
        });
        dPanel.add(IsExpertCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        plExpert.setBackground(new java.awt.Color(204, 204, 204));
        plExpert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        plExpert.setOpaque(false);

        LanguagesJList.setBackground(new java.awt.Color(102, 102, 102));
        LanguagesJList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LanguagesJList.setForeground(new java.awt.Color(255, 255, 255));
        LanguagesJList.setEnabled(false);
        jScrollPane2.setViewportView(LanguagesJList);

        ProgrammingLanguages.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ProgrammingLanguages.setText("Programming Languages:");

        javax.swing.GroupLayout plExpertLayout = new javax.swing.GroupLayout(plExpert);
        plExpert.setLayout(plExpertLayout);
        plExpertLayout.setHorizontalGroup(
            plExpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plExpertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProgrammingLanguages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        plExpertLayout.setVerticalGroup(
            plExpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plExpertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plExpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgrammingLanguages))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        dPanel.add(plExpert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Last Name:");
        dPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("E-Mail:");
        dPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        iconFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dPanel.add(iconFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 11, 160, 160));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("First Name:");
        dPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(dPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 172, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grayNoobwallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

            view.removeProgrammer(cbID, this);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void IsExpertCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsExpertCheckBoxActionPerformed

        this.plExpert.setVisible(IsExpertCheckBox.isSelected());

    }//GEN-LAST:event_IsExpertCheckBoxActionPerformed

    private void cbIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIDItemStateChanged
        prog.get( cbID.getSelectedIndex());
        if(prog.get( cbID.getSelectedIndex()) instanceof ExpertProgrammer)
        {
            this.dPanel.setVisible(true);
            ExpertProgrammer exp = (ExpertProgrammer)prog.get( cbID.getSelectedIndex());
            txtMail.setText(exp.getEmail());
            txtFirstName.setText(exp.getFirstName());
            txtLastName.setText(exp.getLastName());
            view.setImag(this.iconFrame, exp.getIcon());
            IsExpertCheckBox.setSelected(true);
            DefaultListModel<String> modle = new DefaultListModel<String>();
            for(String lang : exp.getLanguages())
            {
                modle.addElement(lang);
            }
            LanguagesJList.setModel(modle);
            this.plExpert.setVisible(true);
        }else{
            this.plExpert.setVisible(false);
            IsExpertCheckBox.setSelected(false);
            Programmer pro = (Programmer)prog.get( cbID.getSelectedIndex());
            txtMail.setText(pro.getEmail());
            txtFirstName.setText(pro.getFirstName());
            txtLastName.setText(pro.getLastName());
            view.setImag(this.iconFrame, pro.getIcon());
        }
    }//GEN-LAST:event_cbIDItemStateChanged

 /**
     * the method gets address of sound file and return the sound for play.
     * @param soundAddress
     * @return sound
     */
    public SoundClass sound(String soundAddress) {          ///////// sound method
        SoundClass sound = new SoundClass(soundAddress);
        return sound;
    }

        /**
     * the method gets address of icon file and return the icon for display.
     * @param iconAddress
     * @return the icon
     */
    public Icon icon(String iconAddress) {          ///////// icon method
        Icon succeedIcon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(iconAddress)));
        return succeedIcon;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox IsExpertCheckBox;
    private javax.swing.JList<String> LanguagesJList;
    private javax.swing.JLabel ProgrammingLanguages;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbID;
    private javax.swing.JPanel dPanel;
    private javax.swing.JLabel iconFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JPanel plExpert;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    // End of variables declaration//GEN-END:variables
}
