/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Aviad
 */
public class IfrmDescription extends javax.swing.JInternalFrame {

    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private javax.swing.JDesktopPane myDesk;
    
    frmCodeEditor frmcodeEditor;
    /**
     * Creates new form IfrmDescription
     * @param view
     * @param myDesk
     * @param frmcodeEditor
     */
    public IfrmDescription(ViewLogic view, javax.swing.JDesktopPane myDesk, frmCodeEditor frmcodeEditor) {
        this.myDesk = myDesk;
        this.view = view;
        this.frmcodeEditor = frmcodeEditor;
        initComponents();
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        this.setSize(desktopSize);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    public String getDescription(){
        return taDescription.getText();
    }
            
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();

        setBorder(null);

        taDescription.setBackground(new java.awt.Color(102, 102, 102));
        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        taDescription.setForeground(new java.awt.Color(255, 255, 255));
        taDescription.setRows(5);
        taDescription.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                taDescriptionPropertyChange(evt);
            }
        });
        taDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taDescriptionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(taDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taDescriptionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_taDescriptionPropertyChange
        
    }//GEN-LAST:event_taDescriptionPropertyChange

    private void taDescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taDescriptionKeyTyped
        if(taDescription.getText().length() > 0){
            frmcodeEditor.enabledNext(true);
        }else{
            frmcodeEditor.enabledNext(false);
        }
    }//GEN-LAST:event_taDescriptionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taDescription;
    // End of variables declaration//GEN-END:variables
}
