/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;

import model.ExpertProgrammer;
import model.Programmer;



/**
 *
 * @author Aviad
 */
public class IfrmAddTeam extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private javax.swing.JDesktopPane myDesk;
    
    private ArrayList<Programmer> prog;
    
    private String fileName;
    /**
     * Creates new form IfrmAddProgrammer
     * @param view
     * @param myDesk
     */
    public IfrmAddTeam(ViewLogic view, javax.swing.JDesktopPane myDesk) {
        this.myDesk = myDesk;
        this.view = view;
        initComponents();
        this.dPanel.setVisible(false);
        this.plExpert.setVisible(false);
        this.txtTeamName.requestFocusInWindow();
        setTitle("Add Team"); //the title of the frame
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        this.setSize(desktopSize);
        prog = view.getAllProgrammers();
       
        for(int i=0;i<prog.size();i++)
            {
                if(prog.get(i).getTeam()==0)
                {
                    
            cbID.addItem(prog.get(i).getId());
           
                }
                else
                {
                     prog.remove(i);
                     i--;
                }
            }
       
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        cbID = new javax.swing.JComboBox<>();
        dPanel = new javax.swing.JPanel();
        txtMail = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        IsExpertCheckBox = new javax.swing.JCheckBox();
        plExpert = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LanguagesJList = new javax.swing.JList<>();
        ProgrammingLanguages = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iconFrame = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtTeamName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 558, 100, 31));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Programmer ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        btnCancel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 558, 100, 31));

        cbID.setBackground(new java.awt.Color(102, 102, 102));
        cbID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbID.setForeground(new java.awt.Color(204, 204, 204));
        cbID.setOpaque(false);
        cbID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIDItemStateChanged(evt);
            }
        });
        getContentPane().add(cbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 150, 26));

        dPanel.setBackground(new java.awt.Color(204, 204, 204));
        dPanel.setOpaque(false);

        txtMail.setEditable(false);
        txtMail.setBackground(new java.awt.Color(102, 102, 102));
        txtMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMail.setForeground(new java.awt.Color(255, 255, 255));
        txtMail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtMail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtFirstName.setEditable(false);
        txtFirstName.setBackground(new java.awt.Color(102, 102, 102));
        txtFirstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        txtLastName.setEditable(false);
        txtLastName.setBackground(new java.awt.Color(102, 102, 102));
        txtLastName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        IsExpertCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        IsExpertCheckBox.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IsExpertCheckBox.setText("Is Expert:  ");
        IsExpertCheckBox.setEnabled(false);
        IsExpertCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        IsExpertCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IsExpertCheckBox.setOpaque(false);
        IsExpertCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsExpertCheckBoxActionPerformed(evt);
            }
        });

        plExpert.setBackground(new java.awt.Color(204, 204, 204));
        plExpert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        plExpert.setOpaque(false);

        LanguagesJList.setBackground(new java.awt.Color(102, 102, 102));
        LanguagesJList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LanguagesJList.setForeground(new java.awt.Color(255, 255, 255));
        LanguagesJList.setEnabled(false);
        jScrollPane2.setViewportView(LanguagesJList);

        ProgrammingLanguages.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ProgrammingLanguages.setText("Programming Languages:");

        javax.swing.GroupLayout plExpertLayout = new javax.swing.GroupLayout(plExpert);
        plExpert.setLayout(plExpertLayout);
        plExpertLayout.setHorizontalGroup(
            plExpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plExpertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProgrammingLanguages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        plExpertLayout.setVerticalGroup(
            plExpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plExpertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plExpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgrammingLanguages))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("E-Mail:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("First Name:");

        javax.swing.GroupLayout dPanelLayout = new javax.swing.GroupLayout(dPanel);
        dPanel.setLayout(dPanelLayout);
        dPanelLayout.setHorizontalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plExpert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IsExpertCheckBox)
                    .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dPanelLayout.createSequentialGroup()
                            .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dPanelLayout.setVerticalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(IsExpertCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plExpert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(dPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        iconFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(iconFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 160, 160));

        lbIcon.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbIcon.setText("Icon:");
        getContentPane().add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Choose...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 100, -1));

        txtTeamName.setBackground(new java.awt.Color(102, 102, 102));
        txtTeamName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTeamName.setForeground(new java.awt.Color(255, 255, 255));
        txtTeamName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(txtTeamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 26));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Team Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grayNoobwallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         final JFrame pa=(JFrame)myDesk.getTopLevelAncestor();
           final JDialog frame=view.getAnimation(pa);
            	  final JInternalFrame curr=this;
                 
                  new Thread(new Runnable(){
                  	
                  @Override
                  public void run(){
                     //time consuming algorithm.
                     enableComponents(pa,false);
                      view.addTeam(txtTeamName,prog.get(cbID.getSelectedIndex()) ,fileName , curr);
                       SwingUtilities.invokeLater(new Runnable(){
                           @Override public void run(){
                        	   enableComponents(pa,true);
                          	 frame.dispose(); 
                                
                    
         	
                         }
                        });
                     
                  }
                  }).start();
     
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIDItemStateChanged
        this.dPanel.setVisible(true);
        if(prog.get( cbID.getSelectedIndex()) instanceof ExpertProgrammer)
        {
            ExpertProgrammer exp = (ExpertProgrammer)prog.get( cbID.getSelectedIndex());
            txtMail.setText(exp.getEmail());
            txtFirstName.setText(exp.getFirstName());
            txtLastName.setText(exp.getLastName());
            IsExpertCheckBox.setSelected(true);
            DefaultListModel<String> modle = new DefaultListModel<String>();
            for(String lang : exp.getLanguages())
            {
                modle.addElement(lang);
            }
            LanguagesJList.setModel(modle);
            this.plExpert.setVisible(true);
        }else{
            Programmer pro =  (Programmer)prog.get( cbID.getSelectedIndex());
            IsExpertCheckBox.setSelected(false);
             this.plExpert.setVisible(IsExpertCheckBox.isSelected());
            txtMail.setText(pro.getEmail());
            txtFirstName.setText(pro.getFirstName());
            txtLastName.setText(pro.getLastName());
        }
    }//GEN-LAST:event_cbIDItemStateChanged

    private void IsExpertCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsExpertCheckBoxActionPerformed

        this.plExpert.setVisible(IsExpertCheckBox.isSelected());
    }//GEN-LAST:event_IsExpertCheckBoxActionPerformed

    
    
     public void enableComponents(Container container, boolean enable) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                enableComponents((Container)component, enable);
            }
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            JFileChooser ch= new JFileChooser();
            ch.setFileFilter(new FileFilter() {
                @Override
                public boolean accept(File f) {
                    if (f.isDirectory()) {
                        return true;
                    }
                    final String name = f.getName();
                    return name.endsWith(".png") || name.endsWith(".jpg")|| name.endsWith(".gif")|| name.endsWith(".jpeg")|| name.endsWith(".bmp")|| name.endsWith(".JPG");
                }
                @Override
                public String getDescription() {
                    return "*.png,*.jpg,*.gif,*.jpeg,*.bmp,*.JPG";
                }
            });
            ch.showOpenDialog(null);
            File f = ch.getSelectedFile();
            if(f!=null)
            {
                    fileName=f.getAbsolutePath();

                    BufferedImage img= ImageIO.read(f);
                    BufferedImage imd=new BufferedImage(iconFrame.getWidth(),iconFrame.getHeight(),BufferedImage.TYPE_INT_RGB);
                    Graphics2D g=imd.createGraphics();
                    g.drawImage(img,0,0,iconFrame.getWidth(),iconFrame.getHeight(),null);
                    this.iconFrame.setVisible(true);
                    this.iconFrame.setIcon(new ImageIcon(imd));

        }
        } catch (IOException ex) {
            Logger.getLogger(IfrmAddProgrammer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox IsExpertCheckBox;
    private javax.swing.JList<String> LanguagesJList;
    private javax.swing.JLabel ProgrammingLanguages;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbID;
    private javax.swing.JPanel dPanel;
    private javax.swing.JLabel iconFrame;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JPanel plExpert;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtTeamName;
    // End of variables declaration//GEN-END:variables
}
